"""add_cz_token_to_client

Revision ID: 283e72540526
Revises: 4898a95e3e53
Create Date: 2026-07-31 06:41:16.895185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283e72540526'
down_revision: Union[str, None] = '4898a95e3e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cz_token_encrypted', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('cz_token_expires', sa.DateTime(), nullable=True))
    op.drop_column('clients', 'cz_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cz_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('clients', 'cz_token_expires')
    op.drop_column('clients', 'cz_token_encrypted')
    # ### end Alembic commands ###
