"""add_client_fields

Revision ID: 47faf25baa44
Revises: a04722be88fc
Create Date: 2026-07-30 09:00:06.613088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47faf25baa44'
down_revision: Union[str, None] = 'a04722be88fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('ceo_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('type', sa.Enum('INDIVIDUAL', 'LEGAL', name='clienttype'), nullable=True))
    op.add_column('clients', sa.Column('kpp', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('confirmation_token', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('subscription_end_date', sa.Date(), nullable=True))
    op.drop_column('clients', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('clients', 'subscription_end_date')
    op.drop_column('clients', 'confirmation_token')
    op.drop_column('clients', 'email_confirmed')
    op.drop_column('clients', 'kpp')
    op.drop_column('clients', 'type')
    op.drop_column('clients', 'ceo_name')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
