"""create_inventory_tables

Revision ID: a04722be88fc
Revises: 343422e678e4
Create Date: 2026-07-30 08:51:19.796157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04722be88fc'
down_revision: Union[str, None] = '343422e678e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='inventorysessionstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('total_mismatches', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_sessions_id'), 'inventory_sessions', ['id'], unique=False)
    op.create_table('inventory_differences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mark_code', sa.String(length=255), nullable=False),
    sa.Column('expected_status', sa.String(length=50), nullable=True),
    sa.Column('actual_status', sa.String(length=50), nullable=True),
    sa.Column('difference_type', sa.Enum('MISSING', 'EXTRA', 'MISMATCH', name='differencetype'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_differences_id'), 'inventory_differences', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_differences_mark_code'), 'inventory_differences', ['mark_code'], unique=False)
    op.create_table('scanned_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mark_code', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_marks_id'), 'scanned_marks', ['id'], unique=False)
    op.create_index(op.f('ix_scanned_marks_mark_code'), 'scanned_marks', ['mark_code'], unique=False)
    op.create_table('write_off_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_write_off_documents_id'), 'write_off_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_write_off_documents_id'), table_name='write_off_documents')
    op.drop_table('write_off_documents')
    op.drop_index(op.f('ix_scanned_marks_mark_code'), table_name='scanned_marks')
    op.drop_index(op.f('ix_scanned_marks_id'), table_name='scanned_marks')
    op.drop_table('scanned_marks')
    op.drop_index(op.f('ix_inventory_differences_mark_code'), table_name='inventory_differences')
    op.drop_index(op.f('ix_inventory_differences_id'), table_name='inventory_differences')
    op.drop_table('inventory_differences')
    op.drop_index(op.f('ix_inventory_sessions_id'), table_name='inventory_sessions')
    op.drop_table('inventory_sessions')
    # ### end Alembic commands ###
