"""remove_unique_email_phone_client

Revision ID: df98c5853ebc
Revises: 47faf25baa44
Create Date: 2026-07-30 09:44:31.634787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df98c5853ebc'
down_revision: Union[str, None] = '47faf25baa44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    # ### end Alembic commands ###
