"""Add email confirmation fields to clients

Revision ID: f1b3fe3d9aab
Revises: 41579749b21d
Create Date: 2026-07-28 16:25:09.281210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b3fe3d9aab'
down_revision: Union[str, None] = '41579749b21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('confirmation_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'clients', ['confirmation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'confirmation_token')
    op.drop_column('clients', 'email_confirmed')
    # ### end Alembic commands ###
